# Generated by Django 5.2.5 on 2025-08-26 14:19

import django.utils.timezone
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=jobs.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
